hwi_oauth_login:
    resource: "@UserBundle/Resources/config/login.yml"
    prefix:   /oauth2/login

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /oauth2/connect

hwi_oauth_connect:
    resource: "@UserBundle/Resources/config/connect.yml"
    prefix:   /oauth2/connect

facebook_login:
    path: /oauth2/login/check_facebook

google_login:
    path: /oauth2/login/check_google

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix:   /admin

admin_controller:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

_sonata_admin:
    resource: .
    type:     sonata_admin
    prefix:   /admin

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

app:
    resource: "@AppBundle/Controller/"
    type:     annotation