hwi_oauth:
    firewall_names: [main]

    connect:
        account_connector: hwi_oauth.user.provider.fosub_bridge

    fosub:
        username_iterations: 30
        properties:
            facebook: facebookId

    resource_owners:
        facebook:
            type:              facebook
            client_id:         "%fb_app_id%"
            client_secret:     "%fb_app_secret%"
            scope:             "public_profile, email"
            #infos_url:        "https://graph.facebook.com/me?fields=id,name,email,picture.type(square)" [Maybe for later]
            options:
                appsecret_proof: true

        google:
            type:              google
            client_id:         "%google_app_id%"
            client_secret:     "%google_app_secret%"
            scope:             "email profile"
