# Liip Imagine Configuration
liip_imagine:
    resolvers:
       default:
          web_path: ~

    filter_sets:
        cache: ~

        navbar_logo:
            quality: 80
            filters:
                thumbnail: { size: [100, 100], mode: outbound }

        post_preview:
            quality: 100
            filters:
                thumbnail: { size: [120, 120], mode: outbound }

        gallery_preview:
            quality: 100
            filters:
                thumbnail: { size: [200, 200], mode: outbound }

        post_view:
            quality: 100
            filters:
                thumbnail: { size: [1000, 900], mode: inset }
