twig:
    form_themes:
        - 'SonataCoreBundle:Form:datepicker.html.twig'

# Sonata Block Configuration
sonata_block:
    default_contexts: [site]
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
        sonata.admin.block.stats: ~
        sonata.admin.block.search_result: ~
        admin.form_javascripts.block: ~

# Sonata Admin Configuration
sonata_admin:
    title: 'Bowling Club Poitevin'
    title_logo: bundles/app/img/logo_bcp.jpg
    show_mosaic_button: false

    templates:
        user_block: UserBundle:Block:user_block.html.twig

    security:
        handler: sonata.admin.security.handler.role

    dashboard:
        blocks:
            - position: top
              class:    col-lg-3 col-xs-6
              type:     sonata.admin.block.stats
              roles:    [ROLE_POST_READER]
              settings:
                code:   bcp.admin.post
                icon:   fa-newspaper-o
                text:   dashboard.stats.post_text
                color:  bg-yellow

            - position: top
              class:    col-lg-2 col-xs-6
              type:     sonata.admin.block.stats
              roles:    [ROLE_PAGE_READER]
              settings:
                code:   bcp.admin.page
                icon:   fa-file-text-o
                text:   dashboard.stats.page_text
                color:  bg-green

            - position: top
              class:    col-lg-2 col-xs-6
              type:     sonata.admin.block.stats
              roles:    [ROLE_USER_READER]
              settings:
                code:   bcp.admin.user
                icon:   fa-users
                text:   dashboard.stats.user_text
                color:  bg-blue

            - position: top
              class:    col-lg-2 col-xs-6
              type:     sonata.admin.block.stats
              roles:    [ROLE_NEWSLETTER_READER]
              settings:
                code:   bcp.admin.newsletter
                icon:   fa-send-o
                text:   dashboard.stats.newsletter_text
                color:  bg-red

            - position: top
              class:    col-lg-3 col-xs-6
              type:     sonata.admin.block.stats
              roles:    [ROLE_COMPETITION_READER]
              settings:
                code:   bcp.admin.competition
                icon:   fa-calendar
                text:   dashboard.stats.competition_text
                color:  bg-yellow

            - position: left
              type:     sonata.admin.block.admin_list
              settings:
                groups:
                    - content

            - position: right
              type:     sonata.admin.block.admin_list
              settings:
                groups:
                    - administration

        groups:
            content:
                label: dashboard.group.content
                label_catalogue: DashboardAdmin
                icon: <i class="fa fa-folder"></i>
                items:
                    - bcp.admin.post
                    - bcp.admin.page
            administration:
                label: dashboard.group.administration
                label_catalogue: DashboardAdmin
                icon: <i class="fa fa-cogs"></i>
                items:
                    - bcp.admin.user
                    - bcp.admin.newsletter
                    - bcp.admin.email
                    - bcp.admin.competition