services:
    user.form.type.roles:
        class: UserBundle\Form\Type\UserAdminRolesType
        arguments:
            - "@user.security.roles_list_builder"
        tags:
            - { name: form.type }