services:
    bcp.competitions_listener:
        class: AppBundle\EventListeners\CompetitionListener
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@bcp.email_sender"
            - "@templating"
            - "@security.token_storage"
            - "%newsletter_from%"
        tags:
            - { name: kernel.event_subscriber }
