services:
    bcp.external_url_generator:
        class: AppBundle\Utils\ExternalUrlGenerator

    bcp.recaptcha:
        class: AppBundle\Utils\Google\ReCaptcha
        arguments:
            - "%google_recaptcha_secret%"

    bcp.contact_provider:
        class: AppBundle\Utils\Newsletter\ContactProvider
        arguments:
            - "@doctrine.orm.entity_manager"

    bcp.newsletter:
        class: AppBundle\Utils\Newsletter\NewsletterManager
        arguments:
            - "@bcp.contact_provider"
            - "@templating"
            - "%newsletter_from%"
            - "@translator"
            - "@bcp.email_sender"

    bcp.email_sender:
        class: AppBundle\Utils\Newsletter\EmailSender

    bcp.user_mailer:
        class: AppBundle\Utils\MailTransportUserMailer
        arguments:
            - "@router"
            - "@templating"
            - "@translator"
            - { confirmation.template: %fos_user.registration.confirmation.template%, resetting.template: %fos_user.resetting.email.template%, from_email: { confirmation: %fos_user.registration.confirmation.from_email%, resetting: %fos_user.resetting.email.from_email% } }
